name: Node CI

on:
  pull_request:
    branches:
      - nuxt
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint, and generate
      run: |
        echo ${{ secrets.APITokens }} | base64 --decode > ./static/config.js
        yarn install
        yarn lint
        yarn generate
      env:
        CI: true

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        emptyCommits: false
